### ISSUE TITLE
scikit-ci.yml: Support commented commands

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-ci#19]
It currently reports a message like this ones:

```bash
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-system/bin/ci", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/__main__.py", line 69, in main
    with_dependencies=args.with_dependencies)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 319, in execute_step
    execute_step(depends[-1], with_dependencies=with_dependencies)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 319, in execute_step
    execute_step(depends[-1], with_dependencies=with_dependencies)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 319, in execute_step
    execute_step(depends[-1], with_dependencies=with_dependencies)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 319, in execute_step
    execute_step(depends[-1], with_dependencies=with_dependencies)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 323, in execute_step
    d.execute_commands(step)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 274, in execute_commands
    cmd, self.env, posix_shell=posix_shell)
  File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/ci/driver.py", line 172, in expand_command
    command = command.replace("\\\n", "")
AttributeError: 'CommentedMap' object has no attribute 'replace'
```

**Comment by jcfr** [comment]
It turns out this was caused by an incorrect command of the form:

```
-  echo "before_install: something else"
```
